FROM php:8.1-fpm-alpine
#FROM php:5.6.36-fpm-jessie

WORKDIR /var/www/html

RUN docker-php-ext-install mysqli
#RUN docker-php-ext-install pdo pdo_mysql
#RUN docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo_mysql
